# Generated by Django 4.0 on 2022-01-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.TextField(default='NA', max_length=200)),
                ('description', models.CharField(default='NA', max_length=700)),
                ('price', models.FloatField(default='0.00')),
                ('stock', models.BooleanField(default=True)),
                ('image', models.ImageField(default='NA', upload_to='media/upload')),
            ],
        ),
    ]
