# Generated by Django 4.0 on 2022-01-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.TextField(default='Fruit'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery',
            field=models.SmallIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default='0.00'),
        ),
    ]
